version: "3.9"

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: patient-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    container_name: kafka-broker
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094;KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - internal_network

  billing-service:
    build:
      context: ./billing-service
    container_name: billing-service
    ports:
      - "9001:9001"
    networks:
      - internal_network
  patient-service:
    build:
      context: ./patient-service
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      - postgres-db
    environment:
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_PORT=9001
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
